### ISSUE TITLE
partially initialized module 'selectors'

### ISSUE THREAD

**Issue by nocomp** [sockysec/Telerecon#9]
hi
i wanted to give it a spin, all install was bug free, but when launching it, it seems i have an issue regarding selectors.
any help would be appreciated.
thxx a lot

└─$ python3 launcher.py
Traceback (most recent call last):
  File "/home/nocomp/tools/osint/Telerecon/launcher.py", line 1, in <module>
    import asyncio
  File "/usr/lib/python3.11/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/lib/python3.11/asyncio/base_events.py", line 23, in <module>
    import socket
  File "/usr/lib/python3.11/socket.py", line 54, in <module>
    import os, sys, io, selectors
  File "/home/nocomp/tools/osint/Telerecon/selectors.py", line 5, in <module>
    import pandas as pd
  File "/usr/lib/python3/dist-packages/pandas/__init__.py", line 7, in <module>
    if 'mips' in platform.uname()[4]:
                 ~~~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3.11/platform.py", line 813, in __getitem__
    return tuple(self)[key]
           ^^^^^^^^^^^
  File "/usr/lib/python3.11/platform.py", line 799, in __iter__
    (self.processor,)
     ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/platform.py", line 794, in processor
    return _unknown_as_blank(_Processor.get())
                             ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/platform.py", line 739, in get
    return func() or ''
           ^^^^^^
  File "/usr/lib/python3.11/platform.py", line 758, in from_subprocess
    import subprocess
  File "/usr/lib/python3.11/subprocess.py", line 245, in <module>
    _PopenSelector = selectors.SelectSelector
                     ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'selectors' has no attribute 'SelectSelector' (most likely due to a circular import)

**Comment by ArrowSyam** [comment]
same for me 😥

**Comment by deepserket** [comment]
The file `parse.py` was renamed into `selectors.py` and it collides with the built in `selectors` module

**Comment by deepserket** [comment]
I've published a fix into my profile, check if it works: https://github.com/deepserket/Telerecon

**Comment by NeonBubbles** [comment]
1. Rename the selectors.py in the directory; for example, selectorss.py or selector.py
2. open the launcher.py in any IDE. 
3. Change 'selectors.py' to the new name in line 86 
('Parse user messages to extract selectors/intel': 'selectorss.py').

**Comment by sockysec** [comment]
Apologies for the slow response, I've been offline over the past week. I have published @deepserket's solution to the issue. This should now be resolved.
